apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: ngdays-2020-hpa
  name: letsscale
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-v1
  targetCPUUtilizationPercentage: 6
